app/main/models.py
from datetime import datetime
from hashlib import md5
from time import time
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
import jwt
from app import app, db, login
from flask import session


@login.user_loader
def load_user(id):
    return User.query.get(int(id))


class User(UserMixin, db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    receipts = db.relationship('Receipt', backref='author', lazy='dynamic')

    def __repr__(self):
        return '<User {}>'.format(self.username) 

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)
    
    def get_reset_password_token(self, expires_in=600):
        return jwt.encode(
            {'reset_password': self.id, 'exp': time() + expires_in},
            app.config['SECRET_KEY'], algorithm='HS256').decode('utf-8')

    @staticmethod
    def verify_reset_password_token(token):
        try:
            id = jwt.decode(token, app.config['SECRET_KEY'],
                            algorithms=['HS256'])['reset_password']
        except:
            return
        return User.query.get(id)


class Receipt(db.Model):
    __tablename__ = 'receipt'
    id = db.Column(db.Integer, primary_key=True)
    sender = db.Column(db.String(64))
    recipient = db.Column(db.String(64))
    notes = db.Column(db.String(140))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    items = db.relationship('Item', backref='receipt', lazy='dynamic',
                                 primaryjoin="Receipt.id == Item.receipt_id")

    def add_receipt_to_session(receipt_form):
        session['receipt_notes'] = form.notes.data
        session['receipt_recipient'] = form.recipient.data
        session['receipt_sender'] = form.sender.data

    def __repr__(self):
        return '<Receipt {}>'.format(self.notes)
    
    def __init__(self, sender, recipient, notes, items):
        self.sender = sender
        self.recipient = recipient
        self.notes = notes

        for item in items:
            new_item = Item(**item)
            self.items.append(new_item)


class Item(db.Model):
    __tablename__ = 'line_item'
    id = db.Column(db.Integer, primary_key=True)
    price = db.Column(db.Float)
    description = db.Column(db.String(64))
    quantity = db.Column(db.Integer)
    receipt_id = db.Column(db.Integer, db.ForeignKey('receipt.id'))

    def serialize(self):
        return {"id": self.id,
                "price": self.price,
                "description": self.description,
                "quantity": self.quantity}

    def __repr__(self):
        return '<Item {}>'.format(self.description)

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import IntegerField, StringField, \
    FormField, TextAreaField, FieldList, Form, \
    SubmitField, PasswordField, BooleanField
from wtforms.validators import DataRequired, ValidationError, \
    Email, EqualTo
from app.main.models import User


class LineItemForm(Form):
    price = IntegerField('Price', validators=[DataRequired()])
    quantity = IntegerField('Quantity', validators=[DataRequired()])
    description = StringField('Description', validators=[DataRequired()])


class ReceiptForm(FlaskForm):
    sender = StringField('Sender', validators=[DataRequired()])
    recipient = StringField('Recipient', validators=[DataRequired()])
    items = FieldList(FormField(LineItemForm),
                      min_entries=0,
                      max_entries=20)
    notes = TextAreaField('Notes')


class PreviewForm(FlaskForm):
    download = SubmitField(label="download")
    send_via_whatsapp = SubmitField(label="send via whatsapp")

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, template_folder='templates')

from app.main import routes

app/main/routes.py
from flask import url_for, render_template, redirect, request, \
    flash, session, make_response
from app import app, db
from app.main import bp
from app.main.forms import ReceiptForm, PreviewForm, LineItemForm
from app.main.models import User, Receipt, Item
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse
import pdfkit


def add_receipt_to_session(receipt_form):
    """
        :param receipt_form: A wtf_form instance
    """
    session['receipt_notes'] = receipt_form.notes.data
    session['receipt_recipient'] = receipt_form.recipient.data
    session['receipt_sender'] = receipt_form.sender.data
    session['receipt_items'] = receipt_form.items.data


def get_receipt_from_session():
    """
        :return receipt_form: A wtf_form instance
    """
    receipt = ReceiptForm()
    receipt.notes = session['receipt_notes']
    receipt.recipient = session['receipt_recipient']
    receipt.sender = session['receipt_sender']
    receipt.items = session['receipt_items']
    return receipt


@bp.route('/', methods=['get', 'post'])
@bp.route('/index', methods=['get', 'post'])
def index():
    form = ReceiptForm()
    lif = LineItemForm()

    if form.validate_on_submit():
        add_receipt_to_session(form)

        receipt = Receipt(sender=form.sender.data,
                          recipient=form.recipient.data,
                          notes=form.notes.data, items=form.items.data)
        db.session.add(receipt)

        if current_user.is_authenticated:
            user = User.query.get(current_user.id) 
            user.receipts.append(receipt)
            db.session.add(user)
        
        db.session.commit()

        return redirect(url_for('preview'), code=302)
    return render_template('receipt.html',
                           form=form, lif=lif)


@bp.route('/preview', methods=['get', 'post'])
def preview():
    form = PreviewForm()
    receipt = get_receipt_from_session()
    
    data = {
        "form": form, 
        "receipt": receipt
    }

    if form.validate_on_submit(): 
        if form.download.data:
            rendered = render_template('actual_preview.html', data=data)
            pdf = pdfkit.from_string(rendered, False)
            response = make_response(pdf)
            response.headers['Content-Type'] = "application/pdf"
            response.headers['Content-Disposition'] = 'attachment; filename=output.pdf'
            return response
        if form.send_via_whatsapp.data:
            pass
 
    return render_template('preview.html', data=data)
        

@bp.route('/download', methods=['get', 'post'])
def download():
    if request.method == 'POST':
        return redirect(url_for('guide', code=200))
    return render_template('download.html')


@bp.route('/guide', methods=['get'])
def guide():
    return render_template('guide.html')


@bp.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    receipts = user.receipts.order_by(Receipt.id).paginate(
        page, app.config['RECEIPTS_PER_PAGE'], False
    )
    next_url = url_for('main.user', username=user.username, page=receipts.next_num) \
        if receipts.has_next else None
    prev_url = url_for('main.user', username=user.username, page=receipts.prev_num) \
        if receipts.has_prev else None
    return render_template('user.html', user=user, receipts=receipts.items,
                            next_url=next_url, prev_url=prev_url)

app/main/templates/actual_preview.html
<h1>Preview</h1>
            sender: {{data.receipt.sender}} <br>
            recipient: {{data.receipt.recipient}} <br>
            notes: {{data.receipt.notes}} <br>
            items:
            {% for item in data.receipt.items %}
                {{item.price}}
                {{item.description}}
                {{item.quantity}} <br>
            {% endfor %}

app/main/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
  receipt app
{% endblock %}

{% block styles %}
{{ super() }}
<style>
    a { 
        color:black;
    }
</style>
{% endblock %}

{% block navbar %}
        <nav class="navbar navbar-light" style="background-color: #f7f7f7; box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);">        
            <div class="collapse navbar-collapse ">
                <ul class="nav navbar-nav">
                    <li class="nav-item active"><a href="{{ url_for('main.index') }}">Simple Receipt</a></li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item"><a href="{{ url_for('main.user', username=current_user.username) }}">Receipts</a></li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_anonymous %}
                    <li class="nav-item"><a href="{{ url_for('auth.login') }}">Login</a></li>
                    {% else %}
                    <li class="nav-item"><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    
{% endblock %}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {# application content needs to be provided in the app_content block #}
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

app/main/templates/download.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block app_content%}
            <h1>Your download is ready!!</h1>
            <h4><a href="{{url_for('main.guide')}}">Why don't you check out our other features?</a> </h4>
{% endblock %}

app/main/templates/guide.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block app_content%}
            <h1>Guide</h1>
            <h4><a href="{{url_for('auth.sign_up')}}">sign up</a><h4>
{% endblock %}

app/main/templates/preview.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block app_content%}
            <h1>Preview</h1>
                sender: {{data.receipt.sender}} <br>
                recipient: {{data.receipt.recipient}} <br>
                notes: {{data.receipt.notes}} <br>
                items:
                {% for item in data.receipt.items %}
                    {{item.price}}
                    {{item.description}}
                    {{item.quantity}} <br>
                {% endfor %}
            <br>
            <form method="post" action="{{ url_for('main.preview') }}">
                    {{ data.form.hidden_tag() }}
                    {{ data.form.csrf_token() }}
                    {{ data.form.download }}
                    {% if current_user.is_authenticated %}
                    {{ data.form.send_via_whatsapp }}  
                    {% endif %}
            </form>
            
{% endblock %}

app/main/templates/receipt.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block scripts %}
{{ super() }}

{# Import JQuery #}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
    /**
    * Adjust indices of form fields when removing line_items
    */

    function adjustIndices(removedIndex){ 
        var $forms = $('.subform');

        $forms.each(function(i){ 
            var $form = $(this); 
            var index = parseInt($form.data('index')); 
            var newIndex = index - 1;

            if (index < removedIndex) {
                // Skip
                return true;
            }

            // Change ID in form itself
            $form.attr('id', $form.attr('id').replace(index, newIndex));
            $form.data('index', newIndex);

            // Change IDs in form inputs
            $form.find('input').each(function(j) {
                var $item = $(this);
                $item.attr('id', $item.attr('id').replace(index, newIndex));
                $item.attr('name', $item.attr('name').replace(index, newIndex));
            });
        });
    }

    /**
    * Remove a form.
    */

    function removeForm() {
        var $removedForm = $(this).closest('.subform');
        var removedIndex = parseInt($removedForm.data('index'));

        $removedForm.remove();

        // Update indices
        adjustIndices(removedIndex);
    }

    /**
    * Add a new form.
    */
    function addForm() {
        var $templateForm = $('#items-_-form');

        if (!$templateForm) {
            console.log('[ERROR] Cannot find template');
            return;
        }

        // Get Last index
        var $lastForm = $('.subform').last();

        var newIndex = 0;

        if ($lastForm.length > 0) {
            newIndex = parseInt($lastForm.data('index')) + 1;
        }

        // Maximum of 20 subforms
        if (newIndex > 20) {
            console.log('[WARNING] Reached maximum number of elements');
            return;
        }

        // Add elements
        var $newForm = $templateForm.clone();

        $newForm.attr('id', $newForm.attr('id').replace('_', newIndex));
        $newForm.data('index', newIndex);

        $newForm.find('input').each(function(idx) {
            var $item = $(this);

            $item.attr('id', $item.attr('id').replace('_', newIndex));
            $item.attr('name', $item.attr('name').replace('_', newIndex));
        });

        // Append
        $('#subforms-container').append($newForm);
        $newForm.addClass('subform');
        $newForm.removeClass('is-hidden');

        $newForm.find('.remove').click(removeForm);
    }


    $(document).ready(function() {
        removeForm();
        $('#add').click(addForm);
        $('.remove').click(removeForm);
    });
</script>
{% endblock %}

{% block styles %}
{{ super() }}
            <style>
                    .is-hidden {
                        display: none;
                    }
   
    h2 {
    font-size: 18px;
    margin: 0 0 15px;
}
.receipt-form {
    width: 340px;
    margin: 30px auto;
}
.receipt-form form {        
    background: #f7f7f7;
    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    padding: 30px;
}    
.form-control, .btn {
    height: 36px;
    border-radius: 2px;
}
.btn {        
    font-size: 15px;
    font-weight: bold;
}
.remember-me {
    margin: 8px 0 0 12px;
}
</style>







{% endblock %}

{% block app_content %}

                <div>
                    
                    <div class="page-header">
                        {% if current_user.is_authenticated%}
                            <h1 id="timeline">Hello, {{ current_user.username }}!</h1>
                            <p>Create a receipt below!</p>
                        {% else %}
                            <h1 id="timeline">Hello!</h1>
                            <p>Create a receipt below!</p>
                        {% endif %}
                    </div>

                    <form class="receipt-form" action="{{url_for('main.index')}}" method="POST" novalidate>
                        {{ form.csrf_token() }}
                        <div class="form-group">
                            {{ wtf.form_field(form.sender) }}
                        </div>
                        <div class="form-group">
                            {{ wtf.form_field(form.recipient) }}
                        </div>
                        
                        <div class="form-group" id="subforms-container">
                            {{ form.items.label }}<br>
                            <div class="col">
                                <a id="add" href="#">Add Item</a>
                            </div>
                            
                                {% for item in form.items %}
                                    <div id="item-{{ item.index0 }}-form" class="subform col" data-index="{{  item.index0 }}"> 
                                        {{ wtf.form_field(item)}}
                                        <a class="remove" href="#">Remove</a>
                                    </div>
                                {% endfor %}
                                                 
                        </div>
                        <div class="form-group">
                            {{ wtf.form_field(form.notes) }}
                        </div>

                        <button type="submit" class="btn btn-success" >preview</button>
                    </form>
                </div>

                

            {# Form template #}
            <div id="items-_-form" class="is-hidden form-row align-items-center" data-index="_">
                <div class="col-auto">
                    <label class="sr-only" for="items-_-price">Price</label>
                    <input class="form-control mb-2" id="items-_-price" name="items-_-price" type="text" value="">    
                </div>
                
                <div class="col-auto">
                    <label class="sr-only" for="items-_-quantity">Quantity</label>
                    <input class="form-control mb-2" id="items-_-quantity" name="items-_-quantity" type="text">   
                </div>

                <div class="col-auto"> 
                    <label class="sr-only" for="items-_-description">Description</label>
                    <input class="form-control mb-2" id="items-_-description" name="items-_-description" type="text">
                </div>

                <div class="col-auto"> 
                    <a class="remove" href="#">Remove</a>
                </div>
  
                
               
            </div>
    
{% endblock %}

app/main/templates/user.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block styles%}
{{super()}}
<style>
</style>
{% endblock %}
{% block app_content%}
<div class="container"> 
    <div class="page-header">
        <h1 id="timeline">Hello, {{ user.username }}!</h1>
        <p>Here are the receipts you've sent so far:</p>
    </div>
    <ul class="timeline">
        {% for receipt in receipts%} 
        <li>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4 class="timeline-title">Receipt - {{receipt.id}}</h4>
              </div>
              <div class="timeline-body">
                <p>sender: {{receipt.sender}}<br>
                    recipient: {{receipt.recipient}}<br>
                    {% for item in receipt.items.all() %}
                        description: {{item.description}}<br>
                        price: {{item.price}}<br>
                        quantity: {{item.quantity}}<br>
                    {% endfor %} 
                    notes: {{receipt.notes}}<br></p>
                    <p><small class="text-muted"><i class="glyphicon glyphicon-time"></i> 11 hours ago</small></p>
              </div>
            </div>
          </li>
          {% endfor %}
    </ul>
    
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> Older receipts
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    Newer receipts <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
</div> 
{% endblock %}